# Generated by Django 4.2 on 2023-05-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('login', models.CharField(max_length=100, verbose_name='Login')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('ty', models.CharField(max_length=50, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('ty', models.CharField(max_length=50, verbose_name='Tipo')),
                ('size', models.CharField(max_length=50, verbose_name='Tamanho do projeto')),
                ('methodology', models.CharField(max_length=50, verbose_name='Metodologia utilizada')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Measy.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Nota')),
                ('comment', models.TextField(verbose_name='Comentário')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Measy.manager')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Measy.metric')),
            ],
        ),
    ]
